# (asin, display name, blurb, labels, from_bestsellers)
O,V,M="Our pick","Value pick","Most bought"
CATS={
"kitchen":dict(name="KitchenWorth",lede="The counter tools people already buy. Our pick, the value pick, and the one that sells most.",card="Knives, pans, and the tools that earn the counter.",bs="Kitchen & Dining; Kitchen Cookware",
 items=[("B008M5U1C2","Victorinox Fibrox Pro 8-Inch Chef's Knife","The knife most home cooks end up keeping. Easy to sharpen, hard to outgrow.",[O],0),
 ("B00006JSUA","Lodge Pre-Seasoned Cast Iron Skillet, 10.25 Inches","The cast iron pan people keep for decades.",[O,V],0),
 ("B009HBKPD0","Tramontina Professional 8-Inch Non Stick Frying Pan","A small nonstick pan for eggs.",[V,M],1),
 ("B0113UZJE2","Etekcity Food Kitchen Scale, Digital Grams and Ounces","Weigh it once and baking stops being guesswork.",[V,M],1),
 ("B00004OCIP","OXO Good Grips Swivel Vegetable Peeler","The peeler that replaced the drawer of cheap ones.",[V],0),
 ("B07YP2VH4B","KitchenAid Classic Multifunction Can Opener","A plain can opener that keeps working.",[M],1),
 ("B079M8FPTW","Rubbermaid Brilliance Food Storage Containers","Clear, stackable containers with lids that seal.",[M],1),
 ("B00FLYWNYQ","Instant Pot Duo 6 Qt 7-in-1 Electric Pressure Cooker","The cooker people already have. Useful, not magical.",[O],0),
 ("B00005UP2P","KitchenAid Artisan 5-Qt Tilt Head Stand Mixer","Buy it if you bake. Skip it if you do not.",[O],0),
 ("B00004OCKT","OXO Good Grips Apple Slicer, Corer & Cutter","One press and the apple is done.",[V],0)],
 vs=("B00006JSUA","Lodge cast iron","B009HBKPD0","Tramontina nonstick","Buy the Lodge if you want one pan that sears and lasts for decades. Buy the Tramontina if you mostly cook eggs and delicate food and want easy release.",[("Job","Searing, roasting, everyday","Eggs, fish, quick sautés"),("Care","Keep it seasoned","Gentle utensils"),("Buy if","You want one pan for life","You want easy release")])),
"clean":dict(name="CleanWorth",lede="Floor tools that still work after a year.",card="Vacuums and mops you buy once and keep.",bs="Vacuum Cleaners & Floor Care; Mops, Buckets & Accessories",
 items=[("B004Q4DRJW","Shark Navigator Lift-Away Upright Vacuum, NV352","The upright most homes end up with. Lifts off for stairs.",[O,M],1),
 ("B07S652B12","Shark Pet Cordless Stick Vacuum, IX141","Grab-and-go cleanup without the cord.",[V,M],1),
 ("B09YS9N7H2","Dyson V8 Cordless Vacuum","The cordless stick that converts to a handheld.",[O],0),
 ("B0DJMP6T3N","BISSELL Little Green Mini Portable Carpet Cleaner","The spot cleaner for spills, pets, and car seats.",[M],1),
 ("B0H34W2MS8","iRobot Roomba 115X Combo Robot Vacuum & Mop","A robot that vacuums, mops, and empties itself.",[M],1),
 ("B0CB6B2JWG","Levoit Cordless Vacuum Cleaner, Anti-Tangle","A cordless stick built for pet hair.",[V,M],1),
 ("B07KG2X2GZ","BLACK+DECKER dustbuster Cordless Handheld Vacuum","The small one you keep on the counter.",[V,M],1),
 ("B00WSWGVZQ","O-Cedar EasyWring Microfiber Spin Mop & Bucket","The spin mop people actually keep using.",[V,M],1),
 ("B07YQDD94M","Swiffer WetJet Spray Mop Starter Kit","Quick weekday floors without a bucket.",[M],1),
 ("B07VVK39F7","Levoit Air Purifier for Home","A quiet purifier for the bedroom.",[O],0)],
 vs=("B004Q4DRJW","Shark Navigator","B07S652B12","Shark Pet cordless","Buy the Navigator if you want one corded upright for the whole house. Buy the cordless stick if you clean in short bursts and hate the cord.",[("Job","Whole-house cleaning","Quick daily pickups"),("Power","Corded","Battery"),("Buy if","You want one main vacuum","You want grab-and-go")])),
"tool":dict(name="ToolWorth",lede="The kit a house uses, not a catalog.",card="The drill, driver, and bits a house actually needs.",bs="Power Tools; Power & Hand Tools",
 items=[("B00IJ0ALYS","DEWALT 20V MAX Cordless Drill and Impact Driver Combo Kit","The drill and driver pair most houses need.",[O,M],1),
 ("B00ET5VMTU","DEWALT 20V Max Drill Driver Kit (DCD771C2)","Just the drill, for less.",[V,M],1),
 ("B002JWSNIS","DEWALT Screwdriver Bit Set, 45-Piece (DW2166)","The bits you reach for, in one case.",[V,M],1),
 ("B0015SBILG","Klein Tools 32500 11-in-1 Screwdriver/Nut Driver","One screwdriver that replaces a drawer of them.",[V],0),
 ("B00002N5NA","Estwing Curved Claw Hammer, 16 oz, E3-16C","A solid hammer that lasts.",[O],0),
 ("B097SXK3FG","WORKPRO Premium Utility Knife","An all-metal box cutter for every job.",[V,M],1),
 ("B07V844YR8","Amazon Basics 36-Piece Allen Wrench/Hex Key Set","Every flat-pack furniture job needs one.",[V,M],1),
 ("B001JT87RY","IRWIN QUICK-GRIP One-Handed Bar Clamp, 6-Inch","A clamp you can set with one hand.",[O],0),
 ("B07QXWG93C","CRAFTSMAN 2.5 Gallon Wet Dry Shop Vacuum","Cleans up after the job, wet or dry.",[M],1),
 ("B0BLMQ8BXB","HOTO 25-Piece Electric Screwdriver Kit","A small powered driver for furniture and fixtures.",[M],1)],
 vs=("B00IJ0ALYS","DEWALT combo kit","B00ET5VMTU","DEWALT drill driver","Buy the combo if you drive long screws or build things. Buy the drill driver alone if you mostly hang shelves and assemble furniture.",[("Job","Drilling and driving","Drilling and light driving"),("Includes","Drill and impact driver","Drill driver"),("Buy if","You build things","You hang and assemble")])),
"yard":dict(name="YardWorth",lede="The outdoor tools that survive a season.",card="Mower, hose, and the gear that survives a season.",bs="Gardening Hand Tools; Gardening & Lawn Care",
 items=[("B0BLT8L937","EGO POWER+ 21\" Cordless Electric Lawn Mower, LM2114","The cordless mower that ends the gas can.",[O],0),
 ("B0CLSDLM57","Greenworks 40V 21in Self-Propelled Lawn Mower","Self-propelled and cordless for less.",[V],0),
 ("B018S68U40","WORX 20V 12\" 2-in-1 Cordless String Trimmer & Edger","Trims and edges with one tool.",[V],0),
 ("B00002N66H","Fiskars Bypass Pruning Shears","The pruners in most garden sheds.",[V,M],1),
 ("B000BX1IB6","Fiskars 28\" Bypass Loppers","For the branches the pruners cannot take.",[M],1),
 ("B004S0PGPM","Fiskars Ergo Garden Trowel","A trowel that digs without bending.",[V,M],1),
 ("B001D1FFZA","Grampa's Weeder Original Stand Up Weed Puller","Pull weeds by the root without kneeling.",[M],1),
 ("B000E28UQU","CHAPIN 20004 SureSpray 1-Gallon Pump Sprayer","A simple sprayer for lawn and garden.",[V,M],1),
 ("B00OHRTKLM","Flexzilla Garden Hose with SwivelGrip, 5/8 in. x 50 ft.","The hose that does not fight you.",[O],0),
 ("B002YPS1KK","Scotts Turf Builder EdgeGuard Mini Broadcast Spreader","Even coverage for small and mid-size lawns.",[V],0)],
 vs=("B0BLT8L937","EGO 21\" mower","B0CLSDLM57","Greenworks 40V mower","Buy the EGO if you want the cordless mower people keep for years. Buy the Greenworks if you want self-propelled for less.",[("Job","Weekly mowing","Weekly mowing"),("Power","Battery","Battery"),("Buy if","You want the top pick","You want value")])),
"bag":dict(name="BagWorth",lede="Bags that outlast the trip.",card="Backpacks and luggage that outlast the trip.",bs="Backpacks; Luggage",
 items=[("B07BL7JXHV","Travelpro Maxlite 5 Softside Carry-On Spinner, 21-Inch","A softside carry-on spinner built to hold up.",[O],0),
 ("B01M0A3BKH","Samsonite Freeform Hardside Carry-On Spinner","A hardside carry-on from a brand that lasts.",[O,M],1),
 ("B071VG5N9D","Amazon Basics 21\" Hardside Carry-On Spinner","The carry-on that does the job for less.",[V,M],1),
 ("B07YNKH8BZ","Wrangler 22.5\" Hardside Spinner Carry-On","A budget hardside that rolls well.",[V,M],1),
 ("B0D14QYX9Y","SwissGear Sion Softside Expandable Spinner Luggage","Softside luggage that expands when you need it.",[M],1),
 ("B09KQ262GM","Osprey Farpoint 40L Travel Backpack","The travel pack for one-bag trips.",[O],0),
 ("B0007QCQGI","JanSport SuperBreak One Backpack","The simple backpack everyone has owned.",[V,M],1),
 ("B006HFJA12","SWISSGEAR 1900 ScanSmart Laptop Backpack","A laptop backpack that lays flat at security.",[M],1),
 ("B002P3XFJ8","Fjällräven Kånken Backpack","The classic boxy daypack.",[O],0),
 ("B0CV5R46SM","Patagonia Black Hole Duffel Bag 40L","A tough duffel for the gym or the weekend.",[O],0)],
 vs=("B01M0A3BKH","Samsonite Freeform","B071VG5N9D","Amazon Basics carry-on","Buy the Samsonite if you fly often and want a brand built for it. Buy the Amazon Basics if you fly a few times a year.",[("Job","Carry-on","Carry-on"),("Shell","Hardside","Hardside"),("Buy if","You fly often","You fly sometimes")])),
"groom":dict(name="GroomWorth",lede="The drawer, not the salon.",card="Trimmers and razors worth keeping in the drawer.",bs="Shaving & Hair Removal; Hair Clippers & Accessories; Hair Cutting Tools",
 items=[("B0BZQTSBWZ","Philips Norelco OneBlade 360 Hybrid Face Trimmer and Shaver","Trim, edge, and shave with one tool.",[O],0),
 ("B0FYRVMDXR","Braun Series 7 Electric Shaver for Men","A foil shaver for a close daily shave.",[O],0),
 ("B01N0993NM","Wahl Color Pro Cordless Hair Clipper & Trimmer","Home haircuts with color-coded guards.",[V,M],1),
 ("B00006IVEN","Wahl Clipper Color Pro Corded Haircutting Kit","The corded kit that keeps going.",[V,M],1),
 ("B0BJ15Z14D","Andis 04780 Professional T-Outliner Trimmer","A professional trimmer for clean lines.",[O],0),
 ("B002A8JO1Q","Merkur 34C Double Edge Razor","A safety razor that makes blades cheap.",[O],0),
 ("B0001LQGPG","Gillette Sensor3 Sensitive Disposable Razor, 4 Razors","Disposables that do the job.",[V,M],1),
 ("B09SGK9FWZ","Harry's Original Razor Blades for Men, 10 Count","Cartridge blades for less.",[M],1),
 ("B00837ZOI0","Proraso Refreshing Shaving Cream for Men","A classic Italian shave cream.",[V],0),
 ("B0000532A2","Revlon Expert Slant Tip Tweezer","A slant tweezer that grips.",[V,M],1)],
 vs=("B0BZQTSBWZ","OneBlade 360","B0FYRVMDXR","Braun Series 7","Buy the OneBlade if you keep stubble and want one tool to trim and edge. Buy the Braun if you want a clean shave every morning.",[("Job","Trim, edge, shave","Daily close shave"),("Style","Hybrid blade","Foil shaver"),("Buy if","You keep stubble","You shave clean")])),
"fit":dict(name="FitWorth",lede="Gear you will still use in six months.",card="Mats, weights, and gear you will still use.",bs="Exercise & Fitness Equipment; Exercise & Fitness Accessories",
 items=[("B00NH9WEUA","Concept2 RowErg Indoor Rowing Machine","The air rower with the PM5 monitor.",[O],0),
 ("B0FRNG2N5H","BowFlex Results Series SelectTech Dumbbells","Adjustable dumbbells that save floor space.",[O],0),
 ("B01LR5RG08","Amazon Basics Neoprene Dumbbell Hand Weights","Light weights for toning and warmups.",[V,M],1),
 ("B0731DFTR2","Amazon Basics Cast Iron Kettlebell","A cast iron bell for swings and squats.",[V],0),
 ("B0BYFFX51Z","Gaiam Premium Yoga Mat, 6mm","A cushioned mat for yoga and floor work.",[V],0),
 ("B0040EGNIU","TriggerPoint Grid 1.0 Foam Roller","The roller for sore legs and backs.",[O],0),
 ("B09DF9NWC7","Tangle-Free Rapid Speed Jump Rope","Cheap cardio that fits in a bag.",[V,M],1),
 ("B07BB3VQ42","Gymreapers Lifting Wrist Straps","Hold the bar longer on heavy pulls.",[M],1),
 ("B07DK9QZV9","Trideer Yoga Ball, Pump Included","For core work, stretching, or a desk chair.",[M],1),
 ("B07KQP1X5T","ATERCEL Workout Gloves","Grip and palm protection for lifting.",[V,M],1)],
 vs=("B0FRNG2N5H","BowFlex SelectTech","B01LR5RG08","Amazon Basics neoprene","Buy the BowFlex if you want a full set of weights in a small space. Buy the neoprene pair if you want light weights for toning and warmups.",[("Job","Strength training","Toning, warmups"),("Weights","Adjustable","Fixed"),("Buy if","You lift","You tone")])),
"bath":dict(name="BathWorth",lede="The things that dry, and the shower.",card="Towels, showers, and the things that dry well.",bs="Bath Products; Bathroom Towels",
 items=[("B08LBN2JPS","Tens Towels 4 Piece Extra Large Bath Towels, 30 x 60","Big towels that dry you off.",[O,M],1),
 ("B00Q7JESL0","Amazon Basics 6-Piece Cotton Towel Set","A full towel set for less.",[V,M],1),
 ("B010S5VXKC","Amazon Basics Fast Drying Cotton Washcloths","Washcloths that dry between uses.",[V,M],1),
 ("B0CFGYFCYL","OLANLY Bathroom Rug, 30x20 Chenille","A soft rug that soaks up the drips.",[V,M],1),
 ("B08QRFZ6TH","Barossa Design Shower Curtain Liner, Clear","A clear liner that keeps the floor dry.",[V,M],1),
 ("B0DQHJR1YB","Rain Shower Head with Handheld Showerhead","Rain head plus a handheld for rinsing.",[M],1),
 ("B01HI1W1V4","Etekcity Digital Body Weight Bathroom Scale","A simple scale that reads fast.",[M],1),
 ("B0CVNGWWX6","simplehuman Liquid Sensor Pump, 9 oz","Touch-free soap at the sink.",[O],0),
 ("B01N28QIJM","simplehuman Butterfly Step Can, 10L Bathroom Trash Can","A small step can that closes quietly.",[O],0),
 ("B001EHVERG","Moen Home Care 18 Inch Stainless Steel Grab Bar","A grab bar for the tub or shower.",[O],0)],
 vs=("B08LBN2JPS","Tens Towels","B00Q7JESL0","Amazon Basics set","Buy the Tens Towels if you want big bath towels. Buy the Amazon Basics set if you want bath, hand, and washcloths for less.",[("Job","Bath towels","Full towel set"),("Pieces","4","6"),("Buy if","You want size","You want a set")])),
"travel":dict(name="TravelWorth",lede="The kit that earns the miles.",card="Headphones, chargers, and kit that earn the miles.",bs="Travel Accessories",
 items=[("B09XS7JWHH","Sony WH-1000XM5 Noise Cancelling Wireless Headphones","Noise cancelling for the plane.",[O],0),
 ("B0CCZ26B5V","Bose QuietComfort Headphones","Comfortable noise cancelling for long trips.",[O],0),
 ("B0GJTXVN9Z","Apple AirTag (2nd Generation), 4 Pack","Know where your bag is.",[O],0),
 ("B0CZ9M6X8Q","Anker Power Bank, 10,000mAh 30W","A pocket battery for a long travel day.",[V],0),
 ("B0B27HX6P7","TESSAN European Travel Plug Adapter, 2 Pack","Plug in across Europe.",[V,M],1),
 ("B07QFTGGYF","travel inspira Digital Luggage Scale","Weigh the bag before the airline does.",[V,M],1),
 ("B07SL2RKJK","BAGSMART Toiletry Bag with Hanging Hook","Hang it up and find everything.",[M],1),
 ("B08S35399Y","BAGAIL 8 Set Packing Cubes","Pack by cube, unpack in seconds.",[V,M],1),
 ("B0D3V61JC8","Loop Quiet 2 Reusable Ear Plugs","Reusable plugs for sleeping on the road.",[O],0),
 ("B0051U7W32","Mack's Ultra Soft Foam Earplugs, 50 Pair","Cheap foam plugs that work.",[V],0)],
 vs=("B09XS7JWHH","Sony WH-1000XM5","B0CCZ26B5V","Bose QuietComfort","Buy the Sony if you want the noise cancelling most travelers pick. Buy the Bose if comfort on long flights matters most.",[("Job","Noise cancelling","Noise cancelling"),("Style","Over-ear","Over-ear"),("Buy if","You want our pick","You want comfort")])),
"watch":dict(name="WatchWorth",lede="Watches you buy once.",card="Watches you buy once and wear for years.",bs="Men's Watches",
 items=[("B07ZJW4WZG","SEIKO 5 Sports Automatic Watch for Men","The automatic most people start with.",[O],0),
 ("B000GAWSDG","Casio F91W Digital Watch","The classic cheap digital.",[V,M],1),
 ("B0094B79CI","Casio AE1200WH Digital Watch","A digital with multiple alarms for little money.",[V,M],1),
 ("B009KYJAJY","Casio MDV106 Analog Watch","A 200M water-resistant analog for less.",[V,M],1),
 ("B08VNR3NRW","Casio Illuminator AE1500WH","A simple digital with a backlight.",[V,M],1),
 ("B071RN6K8C","Timex Men's Expedition Scout 40mm Watch","A field watch that takes a beating.",[M],1),
 ("B004VR9HP2","Timex Weekender 38mm Watch","The easy everyday watch.",[V],0),
 ("B09X1B645K","Citizen Men's Classic Eco-Drive Watch","Eco-Drive, so no battery swaps.",[O],0),
 ("B07WJFS6LH","G-Shock GA-2100 Series Watch","The slim G-Shock.",[O],0),
 ("B0BS1T9J4Y","Garmin Forerunner 265 Running Smartwatch","A running smartwatch that does the job.",[O],0)],
 vs=("B07ZJW4WZG","Seiko 5 Sports","B009KYJAJY","Casio MDV106","Buy the Seiko if you want an automatic you will wear for years. Buy the Casio if you want the same look for far less.",[("Job","Everyday wear","Everyday wear"),("Movement","Automatic","Quartz"),("Buy if","You want mechanical","You want value")])),
}
TAGS={c:f"{c}worth20-20" for c in CATS}
